export const LOAD_STATE = 'LOAD_STATE'
// 正在保存的状态记录
export const IS_SAVING = 'IS_SAVING'
// 保存用户
export const USER_INFO = 'USER_INFO'
// 缓存处理
export const ADD_CACHED_INCLUDE = 'ADD_CACHED_INCLUDE'
export const REMOVE_CACHED_INCLUDE = 'REMOVE_CACHED_INCLUDE'
export const ADD_CACHED_EXCLUDE = 'ADD_CACHED_EXCLUDE'
export const REMOVE_CACHED_EXCLUDE = 'REMOVE_CACHED_EXCLUDE'